name: JoshZaldana
favicon: null
layout_spectrum: 0.26628
typography_spectrum: 0.34032
title: Josh Zaldana Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#434146'
    - '#a3a1a4'
    - '#fbf9fc'
    - '#211e19'
    - '#c8c6c9'
  brandStrength: 0.1875
  lightness: 0.8880524444393814
  saturation: 0.416576741496101
  rhythmicContrast: 0.13878617365844548
purpose: []
