name: JoshZaldana
favicon: null
layout_spectrum: 0.26628
typography_spectrum: 0.34032
title: Josh Zaldana
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#434146'
    - '#a3a1a4'
    - '#fbf9fc'
    - '#211e19'
    - '#c8c6c9'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
