name: Josh Zaldana
favicon: null
layout_spectrum: 0.24243
typography_spectrum: 0.14286
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#2c2a2f'
    - '#a7a5aa'
    - '#57555a'
    - '#f0ebe8'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
