name: JoshZaldana
favicon: null
layout_spectrum: 0.7687239684164524
typography_spectrum: 0.9170570077840239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5278726508840919
  lightness: 0.8880524444393814
  saturation: 0.416576741496101
  rhythmicContrast: 0.13878617365844548
purpose: []
